env:
  browser: true
  commonjs: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 6
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-unused-vars:
    args: none
    - error
